admin:
  password_hash: $2b$12$VgkZucVTM48sLDUIB5UUpe.R3JUJSHjpS6nINd2f.Jl.W3cfTTSUy
  username: admin
app:
  debug: false
  name: Photobooth
  version: 1.0.0
camera:
  device_id: 0
  fps: 30
  resolution:
  - 1920
  - 1080
logging:
  format: '{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}'
  level: INFO
  retention: 30 days
  rotation: 1 day
security:
  bcrypt_rounds: 12
  secret_key: your-super-secret-key-here-change-in-production
  session_timeout: 3600
server:
  host: 0.0.0.0
  port: 8000
  workers: 1
storage:
  allowed_extensions:
  - .jpg
  - .jpeg
  - .png
  - .gif
  max_file_size: 10485760
  upload_dir: uploads
ui:
  fullscreen: true
  language: fr
  theme: dark
printing:
  default_printer: ""
  paper_size: "4x6"
  quality: "normal"
  max_copies: 5
  retry_attempts: 3
  retry_delay: 2
email:
  smtp_server: ""
  smtp_port: 587
  smtp_use_tls: true
  smtp_use_ssl: false
  smtp_username: ""
  smtp_password: ""
  from_email: ""
  from_name: "Photobooth"
  subject_template: "Votre photo Photobooth"
  body_template: ""
  max_attachment_size: 10485760
  thumbnail_size: [300, 300]
  thumbnail_quality: 85
  gdpr_consent_required: true
  gdpr_consent_text: ""
  gdpr_retention_days: 30
  rate_limit_emails: 10
  rate_limit_window: 3600
