# Configuration de sécurité pour Photobooth
security:
  # Clé secrète pour la signature des sessions (à changer en production)
  secret_key: "change_me_in_production_very_long_random_string_here"
  
  # Configuration des sessions
  session_timeout: 3600  # 1 heure
  bcrypt_rounds: 12
  
  # Configuration CORS
  allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:8000"
    - "http://127.0.0.1:8000"
  
  # Hôtes autorisés
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
    - "::1"
  
  # Limitation de débit
  rate_limit_requests: 100  # Requêtes par minute
  rate_limit_window: 60     # Fenêtre en secondes
  
  # Protection contre les attaques par force brute
  max_login_attempts: 5     # Tentatives de connexion
  lockout_duration: 300     # Durée de verrouillage (5 minutes)
  
  # Configuration des cookies
  cookie_secure: false      # True en production avec HTTPS
  cookie_httponly: true
  cookie_samesite: "lax"
  
  # Headers de sécurité
  security_headers:
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"
    x_xss_protection: "1; mode=block"
    referrer_policy: "strict-origin-when-cross-origin"
    content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
